### ISSUE TITLE
Allow JsonSerializable as $data

### ISSUE THREAD

**Issue by crocodile2u** [NanneHuiges/JSend#13]
Would be nice if fail(), success() and __construct() accepted instance of JsonSerializable as $data argument. ATM I have to pass it like this: JSendResponse::fail($errors->jsonSerialize()) which is not really nice, and could be easily improved.

**Comment by NanneHuiges** [comment]
I can't really decide if I want this because I see where you come from, but it also messes up the footprint of those functions, as the current `array` is not going to be able to implement that interface, so it would have to accept both the array and an object implementing that interface. That's not very nice, and stops us from using any typehinting etc.

As this indecision has been going on too long, I'm closing this for now. If you have a PR I would still be inclined to look at it, but I'm not seeing a way without downsides to implement this.
